# 应用配置
application:
  host: localhost
  port: 4001
  passport:
    secret: secretKey
    expiresIn: 24h
# 数据库配置
database:
  - type: postgres
    host: localhost
    port: 5432
    database: admin.hl
    username: postgres
    password: 609bfd3541c7cb84b5c16dcc5a6479be
    autoLoadEntities: true
    synchronize: true
