# 应用配置
application:
  host: localhost
  port: 4001
  passport:
    secret: secretKey
    expiresIn: 24h
# 数据库配置
database:
  - type: postgres
    host: localhost
    port: 5432
    database: admin.hl
    username: postgres
    password: c47926821aa3c2217997999f7fa59483
    autoLoadEntities: true
    synchronize: true
